trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK 8'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build StudentRecordSystem.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build console app'

- script: dotnet build StudentRecordAPI/StudentRecordAPI.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build ASP.NET Core API'
